### ISSUE TITLE
[NeoForge 1.20.1] Crash while connecting to a server via Share to WAN mod

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [sleepingdragoninn/inventory-tabs#10]
https://mclo.gs/FxWWlr7
No clue how relevant all of the info in the title is, but...

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/42d1a044-276c-415f-bea2-16cd56b0812d)

tl;dr: these two things are running in reverse - tick is happening before tags are sent. This really needs to _not_ happen to avoid undefined behaviour, but we can at least prevent the crash.
