### ISSUE TITLE
The icon of the box marked with an item frame is not displayed normally.

### ISSUE THREAD

**Issue by mxxndawn** [sleepingdragoninn/inventory-tabs#11]
The icon of the chest marked with an item frame is not displayed normally.

After aligning all the chests on the wall so that only the sides are visible, I want to install an item frame on the side of the chest to apply a unique icon for each chest, but several icon settings are tangled and don't come out properly.

![스크린샷 2023-12-11 시간 15 46 43](https://github.com/sisby-folk/inventory-tabs/assets/110523657/5a8fccbc-a304-44c3-a16b-55f51d15a71b)
![스크린샷 2023-12-11 시간 15 47 40](https://github.com/sisby-folk/inventory-tabs/assets/110523657/50b89bcd-eebd-4bc7-bd69-7dab71ec9b9e)

**Comment by mxxndawn** [comment]
![Uploading 스크린샷 2023-12-11 시간 15.46.43.png…]()

**Comment by sleepingdragoninn** [comment]
Can reproduce, It's likely just searching a little too far for the frames, we'll fix that next patch.

**Comment by sleepingdragoninn** [comment]
Fixed in 1.0.5, let us know if it reoccurs in another configuration.

https://github.com/sisby-folk/inventory-tabs/assets/55819817/d8b96b06-8e07-4737-b402-86d8ce0a7c11

**Comment by mxxndawn** [comment]
Thank you so much!
I'm having more fun playing thanks to the good mode :)

I'll let you know if there's another problem!
