### ISSUE TITLE
Expanded Storage Multiblocks

### ISSUE THREAD

**Issue by lostopkk** [sleepingdragoninn/inventory-tabs#12]
https://github.com/sisby-folk/inventory-tabs/assets/50776714/ce0af3e3-47ae-4b92-9d66-017b1e778a48

I don't know if this bug where two tabs appear for the same chest only happens with expanded storage, but it's sad if you click on a part of the chest and it opens the same chest unnecessarily.

**Comment by sleepingdragoninn** [comment]
Does this mod just have regular double chests? Or does it allow longer than double.

If these chests use the regular FACING and LEFT/RIGHT/SINGLE states that regular chests use, you should be able to set them to use the `inventory_tabs:block_chest` provider in the config. 

If they use different properties than Vanilla chests, this will instead crash - meaning there needs to be a code integration.

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/8ffab0d3-fd97-4f9c-94ca-e07216c4cca7)

On investigation, expanded storage seems to allow chests to be doubled in any arbitrary direction, meaning the config change won't be sufficient. This can only be solved with an addon.

**Comment by sleepingdragoninn** [comment]
Tried our hand at this over at [expanded-storage#15](https://gitlab.com/Compass_System/expanded-storage/-/merge_requests/15)

**Comment by ghost** [comment]
I'm sorry I had no clue y'all made a PR for this, I've just spent the last hour trying to implement it myself...

Would it be okay to manually pull the changes in and add you as a co-author?

**Comment by ghost** [comment]
Now implemented and released in [Expanded Storage 10.1.0](https://modrinth.com/mod/expanded-storage/version/10.1.0+fabric).
Thanks again for PRing support which actually helped compatibility with Jade & similar projects.
Will add to credits on Modrinth shortly.

**Comment by sleepingdragoninn** [comment]
Thank _you_ for carefully capitalising our name - happy modding!
