### ISSUE TITLE
Slight incompatibility with backpack mods

### ISSUE THREAD

**Issue by Sephoix** [sleepingdragoninn/inventory-tabs#14]
Running 1.20.1 with Fabric.
Both Inmis backpack and traveler's backpack have their gui's overlap with the player inventory tab as shown with the screenshots.
![image_2023-12-13_200514796](https://github.com/sisby-folk/inventory-tabs/assets/85546419/f9519ab8-8f99-48c5-ad9e-86084032f606)
![image_2023-12-13_200530716](https://github.com/sisby-folk/inventory-tabs/assets/85546419/37302e85-0825-4cd3-a3b0-33f0ffdb9d5f)

Here are links to the mods in question.
https://modrinth.com/mod/inmis
https://modrinth.com/mod/travelersbackpack

**Comment by sleepingdragoninn** [comment]
Good catch! You can disable tabs for complex screens that don't have explicit tab placement compatibility like so:

 - In `config/inventory_tabs.toml`, set `configLogging` to `true`
 - Load into a world.
 - In your `logs/latest.log` or launcher log window, ctrl+f for "Screen Handler" - you should find debug output from inventory tabs.
 - This debug output lists all available screen handler types - look for the one related to the problematic screen (e.g. "inmis:backpack")
 - In `config/inventory_tabs.toml`, add those types to the `tabDisplayFilter.deny` array - here's an example with fwaystones:

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/54d00dcb-9399-45c3-9ad4-efac8d27114b)

**Comment by sleepingdragoninn** [comment]
okay so `imnis:backpack` was a complete guess but I checked and that's the correct value i'm pretty sure lol

anyway, config format updated in 1.1.1 to be a lot more clear:

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/19381987-f787-4e3f-bd45-b75d6572096f)

**Comment by Sephoix** [comment]
Got it to partially work!
![image](https://github.com/sisby-folk/inventory-tabs/assets/85546419/c4776d92-e4d7-45e7-8a2b-4af56f289e39)
![image](https://github.com/sisby-folk/inventory-tabs/assets/85546419/5be594af-2169-4d35-90fb-e40ec86f103d)

The values for inmis did work out and I was able to find and add traveler's backpack with the short guide you made. The only issue remaining with inmis seems that their button is hard coded into the players inventory and so there still is a bit of overlap. I didn't even see anything that suggests that button could be toggled in the configs and through their github so for me personally it feels like a take it or leave it situation.

![image](https://github.com/sisby-folk/inventory-tabs/assets/85546419/639db7cc-09c8-4fe3-bd66-cea04465c9b7)

Here is what my config looks like for Inventory tabs for anyone else who has the same issues, and thank you for your assistance greatly! 

![image](https://github.com/sisby-folk/inventory-tabs/assets/85546419/2b5f1d40-f405-4542-9c7c-a3b5cb3b2635)

**Comment by sleepingdragoninn** [comment]
Glad it worked out! we'll probably add some way to mess with the player inventory tab placement in the config at some point, which you can track track under #2
