### ISSUE TITLE
1.20 Experimental Hotfixes (1.20.2+)

### ISSUE THREAD

**Issue by Antstone2898** [sleepingdragoninn/inventory-tabs#17]
This is a feature request.

**Comment by sleepingdragoninn** [comment]
We're not currently supporting the experimental hotfixes / milestone snapshot releases for 1.19, but we'll look into it for 1.20 at some point now that we're compiling against Fabric API - it's not clear how many there's going to be yet.

**Comment by venaminecraft** [comment]
Hoping for a 1.20.2 release 😄

**Comment by Dabbpool** [comment]
i would so appreciate a 1.20.2 release since my servers finally updating from 1.18.2 and i cant update and be happy until i get this. its the only mod i cant play without so far. please done make me have to force myself...

**Comment by SkyDev125** [comment]
I'd really love for the 1.20.4 version ngl

**Comment by sleepingdragoninn** [comment]
We've come up with a decent experimental hotfix policy so i'm going to close this to replace it with a roll-up issue
