### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by dustindmiller** [sleepingdragoninn/inventory-tabs#18]
Would love a dark mode to be more compatible with my Vanilla Tweaks resource pack. I understand all dark mode are not created equal, but something darker (gray) just to have it not contrast so much would be appreciated.

**Comment by sleepingdragoninn** [comment]
Feel free! The textures are [here](https://github.com/sisby-folk/inventory-tabs/blob/1.20/src/main/resources/assets/inventory_tabs/textures/gui/buttons.png) for buttons and [here](https://github.com/sisby-folk/inventory-tabs/blob/1.20/src/main/resources/assets/inventory_tabs/textures/gui/tabs.png) for tabs. We're happy to link any packs on the mod page itself - just let us know which vanilla resource packs they match with!

**Comment by sleepingdragoninn** [comment]
done for free in 1.1.3!

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/b06c564f-c607-431c-8f61-c97db5459a71)
