### ISSUE TITLE
Some containers shouldn't have tabs

### ISSUE THREAD

**Issue by QwertRvg** [sleepingdragoninn/inventory-tabs#19]
Currently all containers with an inventory seem to have an Inventory tab, even if said container doesn't have a GUI 
For instance the Goblet and Jar from Supplementaries show up but their tab doesn't even work.
Menu-style blocks like Waystones from the Waystones mod also use Inventory Tabs, even though they don't have an inventory. Their tab does open their menu though. The tabs look quite strange in said menu though.
![image](https://github.com/sisby-folk/inventory-tabs/assets/89683173/ccf0c321-fc03-4439-8a73-342ddbe97e1b)

**Comment by sleepingdragoninn** [comment]
Please check out the readme! Specifically [modpack configuration](https://github.com/sisby-folk/inventory-tabs#modpack-configuration) - this is fully fixable as-is ^^

**Comment by QwertRvg** [comment]
oh wow, thank you so much!
