### ISSUE TITLE
LevelZ Tab Placements

### ISSUE THREAD

**Issue by Nitjsefnie** [sleepingdragoninn/inventory-tabs#2]
Currently, when opening inventory, the GUI looks like this:
![image](https://github.com/sisby-folk/inventory-tabs/assets/75166987/2d82fdc9-00f7-4bb8-bdf0-8a672408ce24)

**Comment by Nitjsefnie** [comment]
Sources for the mentioned mods:
https://github.com/Globox1997/LevelZ
https://github.com/Globox1997/JobsAddon

**Comment by sleepingdragoninn** [comment]
This is already solvable through the API, but We'll probably add another route by letting users offset the safe zones for tabs in the config.
