### ISSUE TITLE
Compatibility with Resource Packs

### ISSUE THREAD

**Issue by QwertRvg** [sleepingdragoninn/inventory-tabs#22]
The Inventory Tabs look the same as the Creative Tabs do, so would it be possible for the mod to use the Creative Tab's graphic instead of a new one. That way, if any resource pack were to load new Creative Tabs they would auto-apply to the Inventory Tabas as well.

**Comment by sleepingdragoninn** [comment]
done in 1.1.3 by slicing up the creative tab texture to be the correct inventory tabs size. 

Note that on photo-style resource packs, this could create seams!

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/97035319-2427-4201-9919-868bb0cd3bd4)
shown with VT transparent

**Comment by QwertRvg** [comment]
that's great! but after adding this version to my pack the game won't load :(
i don't get a crash tho, it just won't load, not sure why

**Comment by sleepingdragoninn** [comment]
feel free to post a log, sometimes there an error even if the game just hangs on the load screen

**Comment by QwertRvg** [comment]
oh nevermind, i was just dumb
didnt update the dependencies
it works now

and thanks a lot for the resource pack compatibility!!
