### ISSUE TITLE
Blocks without inventories showing in tabs

### ISSUE THREAD

**Issue by Cm4nXD** [sleepingdragoninn/inventory-tabs#23]
When using the mod fabric seasons & seasons extra at the same time as this mod it shows a tab button for the greenhouse glass blocks. these are not storage containers, and also have no accessible menu. 

as a potential solution... could there be an option to configure a blacklist of blocks to not show tabs for in the mod's configuration settings with mod menu perhaps?

**Comment by sleepingdragoninn** [comment]
Please check out the readme! Specifically [modpack configuration](https://github.com/sisby-folk/inventory-tabs#modpack-configuration) - this is fully fixable as-is ^^
