### ISSUE TITLE
Identifiers with periods break the config

### ISSUE THREAD

**Issue by hyperdotbat** [sleepingdragoninn/inventory-tabs#25]
Great that you have a way of disabling certain blocks from appearing in the tabs. Because some are inventories without GUIs etc
Just like the mod [Tom's Simple Storage](https://modrinth.com/mod/toms-storage) does have some.

And while its all good with for example the [Packages mod](https://modrinth.com/mod/packages), Tom's Storage has for no reason a subclass, all his blocks are under ts. so an example id is "toms_storage:ts.inventory_hopper_basic"

Well alright I input all of the incorrect blocks that shouldnt appear
![notepad++_RC0yALrMnf](https://github.com/sisby-folk/inventory-tabs/assets/48921794/e3417385-dad0-4895-b279-0be7e753fa25)

On the first launch of the game it works correctly, it refreshes the list to apparently fix the formatting to work like this:
![xecNITb2Eu](https://github.com/sisby-folk/inventory-tabs/assets/48921794/089ac3fa-33cc-43eb-a1c8-412aeb724fc4)

But on the next reload, it for some reason reshuffles the list and now is broken
![MjQKOMmjgS](https://github.com/sisby-folk/inventory-tabs/assets/48921794/adf64e40-f1ae-4616-9468-82f34e88d734)

**Comment by sleepingdragoninn** [comment]
Due to the nature of this, it's definitely an underlying bug in [kaleido](https://github.com/sisby-folk/kaleido-config), or within its shadowed quiltconfig / nightconfigtoml. We'll see if anything can be done about this, because we'd certainly like all valid IDs to be usable as config values.

**Comment by sleepingdragoninn** [comment]
Looks like there's an [awareness of this issue upstream](https://github.com/QuiltMC/quilt-config/blob/c7c084a1cc408eeec27e49de20673919e6f90e9f/src/main/java/org/quiltmc/config/api/serializer/TomlSerializer.java#L47-L53) - we're looking into what can be done.

**Comment by sleepingdragoninn** [comment]
fixed because quilt config fixed it and we bumped!

**Comment by hyperdotbat** [comment]
Forgot to mention that was on 1.20.1 Fabric, do you know if its also fixed in this version or only on the newest?

**Comment by sleepingdragoninn** [comment]
yep, tested on the 1.20.1 version - just update inventory tabs
