### ISSUE TITLE
Centering logic does not take into account page arrows

### ISSUE THREAD

**Issue by HestiMae** [sleepingdragoninn/inventory-tabs#27]
[InventoryTabsScreen.java#L28](https://github.com/sisby-folk/inventory-tabs/blob/1.20/src/main/java/folk/sisby/inventory_tabs/duck/InventoryTabsScreen.java#L28): `margins / 2 + i * tabWidth` should be centering the tabs in the drawable area but I noticed it doesn't take into account the page arrows.

Here I've set a left offset of -50, but the right arrow still overhangs the right side.
![image](https://github.com/sisby-folk/inventory-tabs/assets/62225435/a643d0be-9481-4c4e-8c5d-610df0f02f36)

**Comment by sleepingdragoninn** [comment]
At first I thought this was a bug too, but I think it's a solvable artifact of using offsets the way we are that's effectively working as intended.

Effectively, if the screenshot above is what you see, this is what the mod sees:

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/45d7d3b7-f858-4d06-a1c5-ec789746bf78)

Which means there's no free space to adjust the arrows - it's still dead center of its safe rendering space.

The solution is to just add a negative offset to the right side as well:

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/5e95b5cf-24ec-4701-830a-9dd1865b8fdd)

(used -60, -14 here and drew in a fake obstruction for clarity)

Thanks for the report! Should help give appropriate config values to later issues that use your PR.
