### ISSUE TITLE
Game crashes when opening inventory with Small Ships Mod

### ISSUE THREAD

**Issue by 24-7-testing** [sleepingdragoninn/inventory-tabs#32]
**Minecraft version:** 1.20.1
**Mod version:** Inventory Tabs v1.1.5+
**Mod-Loader:** Fabric

**Description:** When the Small Ships mod is installed (v2.0.0-b1.0), the game crashes when opening the inventory while piloting a ship. According to the creator of the Small Ships mod, it is an issue with Inventory Tabs not making a simple null check. Please investigate and update accordingly, if at all possible! Thank you!

**Steps to reproduce:** Enter ship as if to sail, press "E" to open inventory, observe crash.

**Log:** See attached.
[crash-2024-02-01_20.47.35-client.txt](https://github.com/sisby-folk/inventory-tabs/files/14142726/crash-2024-02-01_20.47.35-client.txt)

**Comment by sleepingdragoninn** [comment]
Looks like small ships is doing something we don't expect, like overriding the init functionality of its screen - we should be able to account for this with some extra safety checks as mentioned - expect it next hotfix!

**Comment by 24-7-testing** [comment]
Awesome, thanks for the quick reply! I'll watch for the fix!

**Comment by sleepingdragoninn** [comment]
up as 1.1.8 now - let us know if it works!

**Comment by 24-7-testing** [comment]
It works, but now there is another small issue. I will make a separate issue report for it.
