### ISSUE TITLE
single chest isn't detected with a block on the left side up (pictures for reference)

### ISSUE THREAD

**Issue by Aruman-Zen** [sleepingdragoninn/inventory-tabs#34]
when any block is placed up left from the chest side it doesn't show the tab (also happens with trapped chest but not double chest or ender chest)
![image](https://github.com/sisby-folk/inventory-tabs/assets/159113965/32ead986-867c-4639-8c4d-6bd0046e11d8)
![image](https://github.com/sisby-folk/inventory-tabs/assets/159113965/0eea27bf-0274-4865-9d18-780393ff9c66)

**Comment by sleepingdragoninn** [comment]
missed out on checking for single chests in the code. Before:

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/a1797518-17d8-48e8-b34a-8c27ca8f17ca)


After:

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/a5435255-e859-477e-8e79-427d28aaf15a)
