### ISSUE TITLE
not work on 1.20

### ISSUE THREAD

**Issue by KIRUYXAN** [sleepingdragoninn/inventory-tabs#36]
I have this error when I start Fabric 1.20:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 **- Replace mod 'Inventory Tabs' (inventory-tabs) 1.1.8+1.20 with any version that is compatible with:
		 - minecraft 1.20**
	 - Replace mod 'Forge Config API Port' (forgeconfigapiport) 7.0.0 with version 8.0 or later.
More details:
	 - Mod 'LibGui' (libgui) 8.1.0+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'Equipment Compare' (equipmentcompare) 1.3.8 requires version 8.0 or later of mod 'Forge Config API Port' (forgeconfigapiport), but only the wrong version is present: 7.0.0!
	 - Mod 'Inventory Tabs' (inventory-tabs) 1.1.8+1.20 requires version 1.20.1 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'Jankson' (jankson) 6.0.0+j1.2.3 requires version 1.20.1 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'Tinfoiled Cotton Client Commands' (cotton-client-commands) 1.1.0+1.15.2 requires any version between 1.14- (inclusive) and 1.16- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.10+39-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.10+39-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.10+39-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.10+39-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.10+39-main requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	 - Mod 'ViaFabric for 1.19' (viafabric-mc119) 0.4.10+39-main requires any 1.19.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by sleepingdragoninn** [comment]
use minecraft 1.20.1 and use 1.20.1 versions of other mods.

**Comment by KIRUYXAN** [comment]
I did so, but just because of this mod, I had to move 75 mods to 1.20.1, I was lucky that it was in all of them
