### ISSUE TITLE
Bottom-of-screen rendering config

### ISSUE THREAD

**Issue by ghost** [sleepingdragoninn/inventory-tabs#37]
It would be nice to be able to set inventory tabs to be at the bottom or sides of my inventory because they currently block some buttons from other mods and potion effects with EMI active. Having an option to make tabs take up all sides of your inventory like advancement tabs do instead of having scroll buttons could also be fun.

**Comment by sleepingdragoninn** [comment]
There's per-screen customisability for where tabs start and end, but we can add similar for bottom rendering - it's already supported, just not through the config.

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/f03ea454-49ee-4860-ba70-871781d67268)
