### ISSUE TITLE
Create compatibility

### ISSUE THREAD

**Issue by joex92** [sleepingdragoninn/inventory-tabs#38]
Hi,
when using with the Create mod some create blocks that have no inventory are considered as inventory:
![image](https://github.com/sisby-folk/inventory-tabs/assets/645579/2a1bf056-bd8a-4339-b860-6e7f3d64e738)
![image](https://github.com/sisby-folk/inventory-tabs/assets/645579/a17d0ee8-e6d9-40b6-ad27-a6a51f6fe93d)
![image](https://github.com/sisby-folk/inventory-tabs/assets/645579/8aa73495-5aa9-4acb-a728-4e55c5ccb74d)
![image](https://github.com/sisby-folk/inventory-tabs/assets/645579/94bb2914-3c26-4e2c-b087-6ff0451eb173)

not only Create, also the Extended Drawers mod;
![image](https://github.com/sisby-folk/inventory-tabs/assets/645579/bdcf3aee-9e18-44ee-9dc0-5581e2264108)
In this case those are inventory blocks, but they are blocks that have no inventory GUI...

**Comment by sleepingdragoninn** [comment]
Hi there!

This is completely fixable in the mod as-is! Feel free to read the [modpack configuration](https://github.com/sisby-folk/inventory-tabs#modpack-configuration) part of the readme to see how to adjust this yourself.

You're also welcome to post the config file you end up with in this thread to help out the next person.

**Comment by joex92** [comment]
oh no... that's a lot... I see that the configuration doesn't have something like `[modProviderOverrides]` or something like that to disable an entire mod from receiving a tab... otherwise I'll have to add every single block!

**Comment by sleepingdragoninn** [comment]
There are actually valid tab blocks in create unfortunately! that wouldn't be sufficient.

Turning on the debug logger gives you the exact list.

**Comment by sleepingdragoninn** [comment]
Some time ago on a previous create version we did create this list, which are valid tabs: https://github.com/sisby-folk/inventory-tabs/blob/0.6-redo/src/main/java/com/kqp/inventorytabs/api/TabProviderRegistry.java#L102

Not precisely what you need, but a decent reference.

Note that these days tags work as well, so you can use do `#create:toolboxes` etc

**Comment by joex92** [comment]
what i meant is this:
use an override to deny all the create blocks, and the override that override for specific blocks... 😅 
but ok... I'll have to add the blocks... the issue is that is not just create, it's drawers mod, some create addons, and some other blocks from other mods...

**Comment by sleepingdragoninn** [comment]
So it turns out i agree with you - here's your config for 1.2.0 once it releases

```toml
	"create:*" = ""
	"#create:toolboxes" = "inventory_tabs:block_simple_storage"
	"#create:valve_handles" = ""
	"create:stockpile_switch" = "inventory_tabs:block_simple"
	"create:display_link" = "inventory_tabs:block_simple"
	"create:schematicannon" = "inventory_tabs:block_simple"
	"create:schematic_table" = "inventory_tabs:block_simple"
```

**Comment by sleepingdragoninn** [comment]
Done and released - here's a full pack example: https://github.com/sisby-folk/tinkerers-quilt/blob/1.20_modded/config/inventory_tabs.toml#L82
