### ISSUE TITLE
Config Options Don't Show up in Mod Menu (Ver 1.0.2; Fabric)

### ISSUE THREAD

**Issue by Coswics** [sleepingdragoninn/inventory-tabs#4]
There are no Config Options that show up, no button at all in mod menu. (The Config File does generate though)
There should probably be an option that lets you change the clicking sound or turn it off completely though

**Comment by sleepingdragoninn** [comment]
Hey there! Configs for inventory tabs 4 are handled through the `inventory_tabs.toml` file, and we don't have plans to expand the scope to in-game configs. The clicking sound is the minecraft default inventory click - you can change it with any resource pack that changes minecraft's built-in one (including replacing it with a silent file).
