### ISSUE TITLE
Block tab "can interact" raycast isn't completely accurate

### ISSUE THREAD

**Issue by CCheukKa** [sleepingdragoninn/inventory-tabs#40]
There seems to be some jank with inventory blocks being partially covered by non-solid blocks being considered unreachable. This bug seems to be affected by your position as well.

The setup used for testing:
![image](https://github.com/sisby-folk/inventory-tabs/assets/38432731/3644ae16-ae1a-4928-9b3f-dac9ca1b44da)

I am aiming at the yellow shulker box in all of these:
![image](https://github.com/sisby-folk/inventory-tabs/assets/38432731/b7296219-fe05-4e16-9706-4bed88996f83)
![image](https://github.com/sisby-folk/inventory-tabs/assets/38432731/8a8f58e2-f2f9-45ee-b335-6d21c658aabb)
![image](https://github.com/sisby-folk/inventory-tabs/assets/38432731/260d2a73-df1c-4b87-b6e1-45c039c0712b)
![image](https://github.com/sisby-folk/inventory-tabs/assets/38432731/fc6800ea-cd5a-4849-b612-3369115a775d)

**Comment by sleepingdragoninn** [comment]
The jank is simple - the mod isn't omniscient, so to check whether it thinks you can click on a block, it raycasts to 9 different spots on the block and sees if any of them hit it

https://github.com/sisby-folk/inventory-tabs/blob/1.20/src/main/java/folk/sisby/inventory_tabs/util/PlayerUtil.java

If they all miss, you miss out.

I'd be interested to know if a better solution (besides just piling on more raycasts) is even possible - false positives can cause much worse desync and lockup jank.
