### ISSUE TITLE
Crash on Click 

### ISSUE THREAD

**Issue by EreoGaming** [sleepingdragoninn/inventory-tabs#44]
When going into inventory (near interactive blocks) and clicking into the interactive block crashes.

Tested all mods without inventory tabs, inventory tabs is the cause. 

[crash-2024-04-04_20.42.31-client.txt](https://github.com/sisby-folk/inventory-tabs/files/14878547/crash-2024-04-04_20.42.31-client.txt)

**Comment by sleepingdragoninn** [comment]
Inventory tabs doesn't support 1.20.4 - we're just about to publish that version from the PR!

**Comment by joex92** [comment]
on version 1.3.2 of the mod is still crashing: https://mclo.gs/CA1PI72

**Comment by sleepingdragoninn** [comment]
inventory tabs does not support 1.20.4 - it supports 1.18.2, 1.19.2, 1.20.1, and 1.21.0

**Comment by joex92** [comment]
@sisby-folk will it never support 1.20.4 versions?
