### ISSUE TITLE
Better Compatibility with Inventorio

### ISSUE THREAD

**Issue by G4lds** [sleepingdragoninn/inventory-tabs#45]
By default the Compatibility is a little janky.

when the inventory key is pressed the inventorio inventory opens, but using the tabs the vanilla inventory opens.

would be better if the tabs also opened inventorio inventory

**Comment by sleepingdragoninn** [comment]
Best way is for them to mixin into us - inventorio already has some optional mixins for client mod compat, they just need to add one that swaps [PlayerInventoryTab#open](https://github.com/sisby-folk/inventory-tabs/blob/1.20/src/main/java/folk/sisby/inventory_tabs/tabs/PlayerInventoryTab.java#L25) to use their open method, PlayerInventoryTab#isInstant to be false, and then probably head cancel PlayerInventoryTab#close to fix issues with cursor-items.

Feel free to file and quote there.
