### ISSUE TITLE
Crash on world load due to wildcard in [invertedTabsOverride]

### ISSUE THREAD

**Issue by Wojbie** [sleepingdragoninn/inventory-tabs#46]
It seems [invertedTabsOverride] does not accept wildcards. Is this expected implementation or a bug?
After reading README.md i was under impression that wildcards were allowed in all settings?

```
[blockProviderOverrides]
	"cool_mod:incompatible_block" = ""
	"really_cool_mod:*" = ""
```

But attempting to set them in [invertedTabsOverride]

```
# 
# -------------------------------
# 
# Manually choose where to place tabs on a given screen
# false means above, true means below
# null key means the player inventory
# 
[invertedTabsOverride]
	"computercraft:*" = true
	"minecraft:beacon" = false
```

Causes crash on load with this cause

`Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: computercraft:*`

Removing the wildcard solves issue.

**Comment by sleepingdragoninn** [comment]
wildcards were introduced in 1.2 - are you perhaps on a minecraft version we've been lazy about?

**Comment by Wojbie** [comment]
Oh i am really sorry forgot to include that. I am on version 1.20.1
```
inventory-tabs: Inventory Tabs 1.3.0+1.20
	folk_sisby_kaleido-config: kaleido-config 0.2.0+1.2.0-beta.5
```

It was latest one for 1.20.1 i seen on modrinth.
I can provide full crash log if required but would prefer to not having to sanitize it for posting if its not needed.

**Comment by sleepingdragoninn** [comment]
Oh right yeah, I wasn't reading closely enough - wildcards aren't implemented for screen handlers, similar to how tags aren't. 

Does computercraft have a lot of handlers?

**Comment by Wojbie** [comment]
It has 8 so it was no problem to just list them one by one. Thanks for confirming it is not implemented and not me just doing something wrong.

**Comment by sleepingdragoninn** [comment]
All good! I'm going to close this one because I think manually setting handler IDs is reasonable, but if anyone finds this and really does wan't fancy handling for screen handler IDs for a mod with some horrendous number of them, let us know.
