### ISSUE TITLE
Tab Texture is being taken from vanilla assets

### ISSUE THREAD

**Issue by itsMarkiS** [sleepingdragoninn/inventory-tabs#47]
please make the tab texture customizable instead of taking the texture from vanilla
at the moment the texture being taken is from 
minecraft:textures/gui/container/creative_inventory/tabs.png

and for people who uses or who makes resource pack this may be bad, which is also my case...
![image](https://github.com/sisby-folk/inventory-tabs/assets/47507632/5ce229fd-9f37-4511-b960-7f7d4dd18da7)

**Comment by itsMarkiS** [comment]
just like you can change the texture from the buttons in the mod folder, the same should be for the tabs

**Comment by sleepingdragoninn** [comment]
conflicts with #22

**Comment by sleepingdragoninn** [comment]
for your case, I would recommend removing the tabs texture from the resource pack yourself - you can just delete it straight out of the zip.
