### ISSUE TITLE
ignoreWalls config isnt effective!

### ISSUE THREAD

**Issue by Dark-Phoenix-01** [sleepingdragoninn/inventory-tabs#56]
The moment a container goes out of line of sight, the item goes away from the inventory tabs. This happens regardless of ignoreWalls config is set to true or false.
Mod version: 1.3.3+1.21 fabric.

**Comment by Dark-Phoenix-01** [comment]
Any updates on this?

**Comment by CCheukKa** [comment]
`ignoreWalls` is for entities only, as stated in the config file

**Comment by sleepingdragoninn** [comment]
vanilla servers do not support opening blocks though walls - disabling itabs' checks would cause it to lock up whenever you tried. Considering this out of scope!
