### ISSUE TITLE
Inventory Tab Placement

### ISSUE THREAD

**Issue by Chouse-10** [sleepingdragoninn/inventory-tabs#61]
Can't get tabs to render at bottom of inventory. Tried changing the config class but still can't get it working.

**Comment by sleepingdragoninn** [comment]
can't reproduce
![image](https://github.com/user-attachments/assets/c64d3c0a-a1e5-4532-abde-4300bc7c820e)

**Comment by Chouse-10** [comment]
Maybe I'm doing the config wrong. Would you be able to send me the config file that has it correct so I could check

**Comment by sleepingdragoninn** [comment]
`invertTabsByDefault = true`

should do it

**Comment by Chouse-10** [comment]
I think it's an issue on my end then. I'm new to this stuff, bit I still can't get it to work after changing it to true

**Comment by sleepingdragoninn** [comment]
Can you send a copy of your `config/inventory_tabs.toml`, and send a link to your `logs/latest.log` on https://mclo.gs/ ?

That should give me enough info

**Comment by Chouse-10** [comment]
I don't have a .toml file for config anywhere thats part of the issue

**Comment by sleepingdragoninn** [comment]
can you send a screenshot of how the tabs look in your game?

**Comment by Chouse-10** [comment]
![2024-08-24_03 25 07](https://github.com/user-attachments/assets/db8948a2-16e6-44f4-b21d-e60c2a5126aa)

**Comment by Chouse-10** [comment]
They just display normally

**Comment by sleepingdragoninn** [comment]
can you send a screenshot of your `.minecraft/config` folder?

**Comment by Chouse-10** [comment]
Actually it is working now. I wiped my config again file and just had it generate a new one now things are working correctly. Not sure why that didn't work earlier
