### ISSUE TITLE
Incompatible with Tranquil texture pack

### ISSUE THREAD

**Issue by BLUEChester** [sleepingdragoninn/inventory-tabs#64]
Hey,

I'm not sure if this is possible but I would LOVE to see some compatibility with this texture pack:

As I love this pack and your mod equally and can't pick one or the other, i'd love to be able to use them both at the same time:
https://www.planetminecraft.com/texture-pack/tranquil-4147413/

Images of how its glitched:
![2024-09-05_21 01 02](https://github.com/user-attachments/assets/b8852854-d93b-40dc-8d94-e17316e39ba5)

![2024-09-05_21 01 06](https://github.com/user-attachments/assets/4f224232-421e-4572-bee3-7e47b7f6e955)

**Comment by sleepingdragoninn** [comment]
just remove the tab texture from tranquil - itabs4 can't work with tabs that are a different size to vanilla's

**Comment by BLUEChester** [comment]
Ok great will do, thanks
