### ISSUE TITLE
Can't disable block(hopper)

### ISSUE THREAD

**Issue by DontiMonti** [sleepingdragoninn/inventory-tabs#65]
If I did everything correctly, it should work, and the hopper should not be displayed on top, but it is displayed
```# 
# -------------------------------
# 
# Manually set whether tabs should be shown on a given screen
# 
[screenOverrides]
	"minecraft:hopper" = false
	"minecraft:smoker" = false
```

**Comment by DontiMonti** [comment]
Minecraft 1.21.1
Mod version: 1.4.0+1.21

**Comment by sleepingdragoninn** [comment]
nope, wrong section of the config - that controls whether tabs appears while you're looking _at_ a hopper, and does not accept block IDs only screen handler IDs.
